let currentUser=null;
const $=s=>document.querySelector(s);
async function api(url,opts={}){const r=await fetch(url,opts);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Request failed");return d}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").hidden=false}
function closeModal(){$("#modal").hidden=true}
function authForm(mode="login"){
return `<p class="kicker">SPONSOR PORTAL</p><h2>${mode==="login"?"Sign in":"Create sponsor account"}</h2>
${mode==="register"?`<form class="form" id="registerForm"><label>Your name<input name="name" required></label><label>Organisation<input name="organisation" required></label><label>Country<input name="country" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="btn">Create account</button><p>Already registered? <a href="#" onclick="openAuth('login');return false">Sign in</a></p></form>`:
`<form class="form" id="loginForm"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="btn">Sign in</button><p>New partner? <a href="#" onclick="openAuth('register');return false">Create an account</a></p></form>`}`}
function openAuth(mode="login"){openModal(authForm(mode));setTimeout(()=>{const form=$("#"+(mode==="login"?"loginForm":"registerForm"));form.onsubmit=async e=>{e.preventDefault();try{const d=await api("/api/"+(mode==="login"?"login":"register"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});currentUser=d.user;closeModal();updateAuth();loadDashboard();alert("Welcome, "+currentUser.name+"!");}catch(err){form.insertAdjacentHTML("afterbegin",`<div class="error">${err.message}</div>`)}}},0)}
async function updateAuth(){const d=await api("/api/session");currentUser=d.user;$("#dashLink").hidden=!currentUser;$("#adminLink").hidden=!(currentUser&&currentUser.role==="admin");$("#authBtn").textContent=currentUser?"Dashboard":"Sponsor Login";$("#authBtn").onclick=()=>currentUser?location.hash="dashboard":openAuth("login")}
async function loadProjects(){const q=$("#search").value,category=$("#category").value;const data=await api("/api/projects?q="+encodeURIComponent(q)+"&category="+encodeURIComponent(category));$("#projectCount").textContent=data.length;$("#projectsGrid").innerHTML=data.map(p=>`<article class="card"><span class="badge">${p.category}</span><h3>${p.title}</h3><p>${p.summary}</p><div class="bottom"><span class="pill">${p.location}</span><span class="pill">Target: ${p.target_beneficiaries}</span>${p.budget_usd?`<span class="pill">Indicative: US$${Number(p.budget_usd).toLocaleString()}</span>`:""}<a href="/api/proposals/${encodeURIComponent(p.proposal_file)}">Download proposal ↓</a><button class="btn small" onclick="applyProject(${p.id})">Partner / Apply</button></div></article>`).join("")||"<p>No projects match your search.</p>"}
async function applyProject(id){if(!currentUser)return openAuth("login");const p=await api("/api/projects/"+id);openModal(`<p class="kicker">PARTNERSHIP APPLICATION</p><h2>${p.title}</h2><form class="form" id="applyForm" enctype="multipart/form-data"><input type="hidden" name="project_id" value="${p.id}"><label>Indicative amount (USD)<input name="amount_usd" type="number" min="0" step="100"></label><label>Partnership proposal / message<textarea name="message" rows="6" required placeholder="Tell SOF what you would like to support or provide."></textarea></label><label>Supporting document (optional)<input name="attachment" type="file" accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx"></label><button class="btn">Submit application</button></form>`);$("#applyForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/applications",{method:"POST",body:new FormData(e.target)});closeModal();loadDashboard();alert("Application submitted successfully.");}catch(err){e.target.insertAdjacentHTML("afterbegin",`<div class="error">${err.message}</div>`)}}}
async function loadOpps(){const data=await api("/api/opportunities");$("#opps").innerHTML=data.length?data.map(o=>`<article class="opp"><span class="status">${o.status}</span><p><b>${o.funder}</b> • ${o.sector}</p><h3>${o.title}</h3><p>${o.notes||"Verified funding opportunity to monitor."}</p>${o.amount?`<p><b>Funding:</b> ${o.amount}</p>`:""}${o.deadline?`<p><b>Deadline:</b> ${o.deadline}</p>`:""}${o.url?`<p><a href="${o.url}" target="_blank" rel="noopener">Official source →</a></p>`:""}${currentUser?`<button class="btn small" onclick="subscribe(${o.id})">Alert me</button>`:`<button class="btn small" onclick="openAuth('login')">Sign in for alerts</button>`}</article>`).join(""):"<p>No opportunities have been published yet. Administrators can add verified calls to the database."}
async function subscribe(id){try{await api("/api/opportunities/"+id+"/subscribe",{method:"POST"});alert("You are subscribed to this opportunity.");loadDashboard()}catch(e){alert(e.message)}}
async function loadDashboard(){if(!currentUser)return;const d=await api("/api/dashboard");$("#dashboard").hidden=false;$("#dash").innerHTML=`<div class="dashcards"><div class="dashcard"><strong>${d.applications.length}</strong><div>Applications</div></div><div class="dashcard"><strong>${d.alerts.length}</strong><div>Opportunity alerts</div></div><div class="dashcard"><strong>${d.user.organisation}</strong><div>Registered organisation</div></div></div><h3>My Sponsor KYC</h3><div class="notice">International sponsors can submit organisation verification information. SOF staff review it before funding decisions.</div>
<form class="form" id="kycForm"><label>Legal organisation name<input name="legal_name" required></label><label>Registration number<input name="registration_no"></label><label>Country<input name="country" required></label><label>Website<input name="website"></label><label>Contact person<input name="contact_person"></label><label>Registration / verification document<input name="document" type="file"></label><button class="btn">Submit / update KYC</button></form>
<h3>My applications</h3><div class="tablewrap"><table><thead><tr><th>Project</th><th>Sector</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>${d.applications.map(a=>`<tr><td>${a.title}</td><td>${a.category}</td><td>${a.amount_usd?`US$${Number(a.amount_usd).toLocaleString()}`:"—"}</td><td>${a.status}</td><td>${a.created_at}</td></tr>`).join("")||"<tr><td colspan='5'>No applications yet.</td></tr>"}</tbody></table></div><h3>My opportunity alerts</h3><div class="tablewrap"><table><thead><tr><th>Funder</th><th>Opportunity</th><th>Sector</th><th>Deadline</th></tr></thead><tbody>${d.alerts.map(a=>`<tr><td>${a.funder}</td><td>${a.title}</td><td>${a.sector}</td><td>${a.deadline||"Monitor"}</td></tr>`).join("")||"<tr><td colspan='4'>No alerts subscribed.</td></tr>"}</tbody></table></div>`}

async function loadAdmin(){
  if(!currentUser || currentUser.role!=="admin") return;
  $("#admin").hidden=false;
  const o=await api("/api/admin/overview");
  $("#adminOverview").innerHTML=Object.entries(o).map(([k,v])=>`<div class="dashcard"><strong>${v}</strong><div>${k.replace(/([A-Z])/g," $1")}</div></div>`).join("");
  const sponsors=await api("/api/admin/sponsors");
  const projects=await api("/api/admin/projects");
  const apps=await api("/api/admin/applications");
  $("#adminPanels").innerHTML=`
  <h3>1. Sponsor KYC</h3><div class="tablewrap"><table><thead><tr><th>Organisation</th><th>Email</th><th>Country</th><th>KYC</th><th>Action</th></tr></thead><tbody>
  ${sponsors.map(s=>`<tr><td>${s.organisation}</td><td>${s.email}</td><td>${s.country}</td><td>${s.kyc_status}</td><td>${s.kyc_status!=="approved"?`<button class="btn small" onclick="reviewKyc(${s.id},'approved')">Approve</button> <button class="btn small" onclick="reviewKyc(${s.id},'rejected')">Reject</button>`:"✓ Verified"}</td></tr>`).join("")}</tbody></table></div>
  <h3>2. Project Approval</h3><div class="tablewrap"><table><thead><tr><th>Project</th><th>Sector</th><th>Decision</th><th>Action</th></tr></thead><tbody>
  ${projects.map(p=>`<tr><td>${p.title}</td><td>${p.category}</td><td>${p.decision}</td><td><button class="btn small" onclick="reviewProject(${p.id},'approved')">Approve</button> <button class="btn small" onclick="reviewProject(${p.id},'rejected')">Reject</button></td></tr>`).join("")}</tbody></table></div>
  <h3>3–10. Application Lifecycle</h3><div class="tablewrap"><table><thead><tr><th>ID</th><th>Organisation</th><th>Project</th><th>Application</th><th>KYC</th><th>Due diligence</th><th>Funding</th><th>Implementation</th><th>Workflow</th></tr></thead><tbody>
  ${apps.map(a=>`<tr><td>#${a.id}</td><td>${a.organisation}</td><td>${a.title}</td><td>${a.status}</td><td>${a.kyc_status}</td><td>${a.dd_status}</td><td>${a.funding_status}</td><td>${a.implementation_status}</td><td><button class="btn small" onclick="openWorkflow(${a.id},'${String(a.title).replace(/'/g,"\\'")}')">Manage</button></td></tr>`).join("")}</tbody></table></div>`;
}
async function reviewKyc(id,status){await api("/api/admin/kyc/"+id+"/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});loadAdmin()}
async function reviewProject(id,decision){await api("/api/admin/projects/"+id+"/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision,score:100,note:"Reviewed in SOF Admin"})});loadAdmin()}
async function openWorkflow(id,title){
  const d=await api("/api/admin/lifecycle/"+id);
  openModal(`<p class="kicker">APPLICATION #${id}</p><h2>${title}</h2>
  <div class="notice">Lifecycle: Application Review → Due Diligence → Funding → Implementation → M&E → Donor Reports</div>
  <h3>Application Review</h3><div class="form"><select id="wfStatus"><option>under_review</option><option>shortlisted</option><option>approved</option><option>rejected</option><option>on_hold</option></select><button class="btn" onclick="wfReview(${id})">Update review</button></div>
  <h3>Due Diligence</h3><form class="form" id="ddForm"><textarea name="checks" rows="3" placeholder="Registration, governance, financial controls, safeguarding, references, conflicts, sanctions screening..." required>${d.dueDiligence?.checks||""}</textarea><select name="risk_level"><option>low</option><option ${d.dueDiligence?.risk_level==="medium"?"selected":""}>medium</option><option ${d.dueDiligence?.risk_level==="high"?"selected":""}>high</option></select><select name="status"><option>pending</option><option>completed</option><option>requires_remediation</option></select><input name="note" placeholder="Reviewer note"><button class="btn">Save due diligence</button></form>
  <h3>Funding</h3><form class="form" id="fundForm"><input name="approved_amount_usd" type="number" placeholder="Approved amount USD" required><select name="status"><option>approved</option><option>funded</option><option>on_hold</option></select><input name="agreement_file" placeholder="Agreement file reference"><input name="note" placeholder="Funding note"><button class="btn">Save funding decision</button></form>
  <h3>Implementation</h3><form class="form" id="implForm"><input name="start_date" type="date"><input name="end_date" type="date"><textarea name="milestones" rows="3" placeholder="Milestones">${d.implementation?.milestones||""}</textarea><select name="status"><option>not_started</option><option>active</option><option>completed</option><option>paused</option></select><input name="note" placeholder="Implementation note"><button class="btn">Save implementation plan</button></form>
  <h3>M&E</h3><form class="form" id="monForm" enctype="multipart/form-data"><input name="metric" placeholder="Metric / indicator" required><input name="target" placeholder="Target"><input name="actual" placeholder="Actual"><input name="reporting_period" placeholder="Reporting period"><input name="evidence" type="file"><button class="btn">Add M&E result</button></form>
  <h3>Donor Report</h3><form class="form" id="repForm" enctype="multipart/form-data"><input name="title" placeholder="Report title" required><input name="period" placeholder="Reporting period"><textarea name="summary" rows="4" placeholder="Executive summary" required></textarea><input name="report" type="file"><button class="btn">Publish report record</button></form>`);
  $("#ddForm").onsubmit=async e=>{e.preventDefault();await api("/api/admin/due-diligence/"+id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert("Due diligence saved.");};
  $("#fundForm").onsubmit=async e=>{e.preventDefault();await api("/api/admin/funding/"+id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert("Funding decision saved.");};
  $("#implForm").onsubmit=async e=>{e.preventDefault();await api("/api/admin/implementation/"+id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert("Implementation plan saved.");};
  $("#monForm").onsubmit=async e=>{e.preventDefault();await api("/api/admin/monitoring/"+id,{method:"POST",body:new FormData(e.target)});e.target.reset();alert("M&E result saved.");};
  $("#repForm").onsubmit=async e=>{e.preventDefault();await api("/api/admin/reports/"+id,{method:"POST",body:new FormData(e.target)});e.target.reset();alert("Donor report saved.");};
}
async function wfReview(id){await api("/api/admin/applications/"+id+"/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:$("#wfStatus").value})});alert("Application review updated.");loadAdmin()}

setTimeout(()=>{const f=$("#kycForm");if(f)f.onsubmit=async e=>{e.preventDefault();try{await api("/api/kyc",{method:"POST",body:new FormData(f)});alert("KYC submitted for SOF review.");}catch(err){alert(err.message)}}},0);
async function logout(){await api("/api/logout",{method:"POST"});currentUser=null;$("#dashboard").hidden=true;updateAuth();alert("You have been logged out.")}
$("#menu").onclick=()=>$(".links").classList.toggle("open");$("#authBtn").onclick=()=>openAuth("login");$("#search").oninput=loadProjects;$("#category").onchange=loadProjects;
(async()=>{await updateAuth();await loadProjects();await loadOpps();if(currentUser)loadDashboard();if(currentUser&&currentUser.role==="admin")loadAdmin()})()
